openapi: 3.0.3
info:
  title: ECL310 API
  contact:
    email: apiteam@swagger.io
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: health
    description: Information about application's health
  - name: system
    description: Request ECL310 system details
paths:
  /health:
    get:
      tags:
        - health
      summary: Get a health status
      operationId: getHealth
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthResponse'          
  /system/info:
    get:
      tags:
        - system
      summary: Get system info
      operationId: getSystemInfo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSystemInfoResponse'
  /system/circuits:
    get:
      tags:
        - system
      summary: Get all circuits' states.
      operationId: getSystemCircuits
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSystemCircuitsResponse'
  /system/circuits/{circuitNo}:
    get:
      tags:
        - system
      summary: Get individual circuit's state.
      operationId: getSystemCircuit
      parameters:
        - in: path
          name: circuitNo
          schema:
            type: integer
            minimum: 1
            maximum: 3
          required: true
          description: Circuit ID. Circuit 1 is the heating, circuit 2 warm water. Circuit 3 is unknown but theoretically possible.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSystemCircuitResponse'
components:
  schemas:
    GetHealthResponse:
      title: GetHealthResponse
      type: object
      properties:
        status:
          type: string
      required:
        - status
    GetSystemInfoResponse:
      type: object
      properties:
        hardware_revision:
          type: string
        software_version:
          type: integer
        serial_number:
          type: integer
          format: int64
        address_type:
          type: string
          enum:
            - DHCP
            - STATIC
        ip_address:
          type: string
        netmask:
          type: string
        gateway:
          type: string
        application:
          type: string
        application_version:
          type: string
        production_year:
          type: integer
          minimum: 2000
        production_week:
          type: integer
          minimum: 1
          maximum: 53
      required:
        - hardware_revision
        - software_version
        - serial_number
        - address_type
        - ip_address
        - netmask
        - gateway
        - application
        - application_version
        - production_year
        - production_week
    GetSystemCircuitsResponse:
      type: object
      properties:
        heating:
          $ref: '#/components/schemas/GetSystemCircuitResponse'
        warm_water:
          $ref: '#/components/schemas/GetSystemCircuitResponse'
        circuit3:
          $ref: '#/components/schemas/GetSystemCircuitResponse'
      required:
        - heating
        - warm_water
    GetSystemCircuitResponse:
      type: object
      properties:
        mode:
          type: string
          enum:
            - MANUAL                # 0
            - SCHEDULED             # 1
            - CONSTANT_COMFORT_TEMP # 2
            - CONSTANT_SETBACK_TEMP # 3
            - FROST_PROTECTION      # 4
        status:
          type: string
          enum:
            - SETBACK     # 0
            - PRE_COMFORT # 1
            - COMFORT     # 2
            - PRE_SETBACK # 3
      required:
        - mode
        - status
#  requestBodies:
